# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lagoon < Formula
  desc "amazee.io's local development helper tool"
  homepage "https://github.com/uselagoon/lagoon-cli"
  version "0.11.10"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.10/lagoon-cli-v0.11.10-darwin-amd64.tar.gz"
      sha256 "bad23dd7c7dab205cc9cf06af0bf94a79b9da99a620d249e8a8fe6ce8b4408ea"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.10/lagoon-cli-v0.11.10-darwin-arm64.tar.gz"
      sha256 "1a6e01071cb02c4f997b00714bbff946b3b5b26c38c9d02fc51dc987bf5ca0ae"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.10/lagoon-cli-v0.11.10-linux-amd64.tar.gz"
      sha256 "84a3219a672ce233c2ba972c4c55bc67a69f8e67950ac23b22046c7a29835942"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.10/lagoon-cli-v0.11.10-linux-arm64.tar.gz"
      sha256 "c6c5e3c5d89657e033214a70d81c7b40ad2fffd0b7eb319bdaa1ef0ec6562f4a"
    end
  end

  def install
    bin.install "lagoon"
  end

  test do
    system "#{bin}/lagoon version"
  end
end
