# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lagoon < Formula
  desc "amazee.io's local development helper tool"
  homepage "https://github.com/tobybellwood/lagoon-cli"
  version "0.11.7-rc.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.7-rc.7/lagoon-cli-v0.11.7-rc.7-darwin-arm64.tar.gz"
      sha256 "3e9772d5119f651c9367d8bb419d2eeec0d540df322e7f3731d2c8e4d384e5de"

      def install
        bin.install "lagoon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.7-rc.7/lagoon-cli-v0.11.7-rc.7-darwin-amd64.tar.gz"
      sha256 "df7d0230e60c3cef8d70d31f3cd41a3e3f08bc7ebbb0dbb1f0b328151bf16663"

      def install
        bin.install "lagoon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.7-rc.7/lagoon-cli-v0.11.7-rc.7-linux-arm64.tar.gz"
      sha256 "7fc4e50901e0aa83a68e0358c468c471c8f405938ed8ee10829fb0172da554ad"

      def install
        bin.install "lagoon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobybellwood/lagoon-cli/releases/download/v0.11.7-rc.7/lagoon-cli-v0.11.7-rc.7-linux-amd64.tar.gz"
      sha256 "d13ca637ce7d0035b82dd25e9b7b8fd3088105a1207cd60e135a777e9471bf8b"

      def install
        bin.install "lagoon"
      end
    end
  end

  test do
    system "#{bin}/lagoon version"
  end
end
